version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:5.6.16-alpine
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m -Xmn128m