version: '3'
services:
  mongo:
    image: mongo:4.1.11
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      # 初始化用户名
      - MONGO_INITDB_ROOT_USERNAME=admin
      # 初始化密码
      - MONGO_INITDB_ROOT_PASSWORD=admin