version: '3'
services:
  kong-database:
    image: postgres:9.6-alpine 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    container_name: kong-database

  kong:
    image: kong:1.1.2-alpine
    restart: always
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=127.0.0.1
      - KONG_PG_PORT=5432
      - KONG_PG_USER=kong
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444
    container_name: kong

  kong-dashboard:
    image: pantsel/konga:0.14.1
    links:
      - kong:kong
      - kong-database:kong-database
    environment:
      - TOKEN_SECRET=1236fbxjayenxaefew
      - DB_ADAPTER=postgres
      - DB_URI=postgresql://kong:kong@127.0.0.1:5432/konga
      - NODE_ENV=production
    ports:
      - 1337:1337
    container_name: kong-dashboard
